[package]
name = "xgt"
version = "0.1.0"
edition = "2021"
authors = ["Anicet Ebou <anicet.ebou@gmail.com>"]
description = "xgt enables efficient querying and parsing of GTDB data"
homepage = "https://github.com/Ebedthan/xgt"
categories = ["command-line-utilities"]
keywords = ["bioinformatics"]

[dependencies]
anyhow = "1.0.69"
clap = "4.1.8"
reqwest = { version = "0.11.14",  features = ["blocking", "json"] }
serde = { version ="1.0.153", features = ["derive"] }
serde_json = "1.0.94"

[dev-dependencies]
mockito = "1.0.2"

[profile.release]
opt-level = 3
debug = true
overflow-checks = false
lto = 'thin'
panic = 'abort'
incremental = false

[[bin]]
name = "xgt"
path = "src/main.rs"
bench = false